// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Start Here',
      link: {type: 'doc', id: 'start-here/how-to-use-this-playbook'},
      items: [{type: 'autogenerated', dirName: '00-start-here'}],
    },
    {
      type: 'category',
      label: 'Foundations',
      link: {type: 'doc', id: 'foundations/marketing-philosophy'},
      items: [{type: 'autogenerated', dirName: '01-foundations'}],
    },
    {
      type: 'category',
      label: 'Trust & Relationships',
      link: {type: 'doc', id: 'trust-and-relationships/referrals-checklist'},
      items: [{type: 'autogenerated', dirName: '02-trust-and-relationships'}],
    },
    {
      type: 'category',
      label: 'Strategy',
      link: {type: 'doc', id: 'strategy/strategy-checklist'},
      items: [{type: 'autogenerated', dirName: '03-strategy'}],
    },
    {
      type: 'category',
      label: 'Digital Presence',
      link: {type: 'doc', id: 'digital-presence/platform-website-and-gmb-checklist'},
      items: [{type: 'autogenerated', dirName: '04-digital-presence'}],
    },
    {
      type: 'category',
      label: 'Content',
      link: {type: 'doc', id: 'content/content-marketing-checklist'},
      items: [{type: 'autogenerated', dirName: '05-content'}],
    },
    {
      type: 'category',
      label: 'Paid Media',
      link: {type: 'doc', id: 'paid-media/paid-media-philosophy'},
      items: [{type: 'autogenerated', dirName: '06-paid-media'}],
    },
    {
      type: 'category',
      label: 'Sales Enablement',
      link: {type: 'doc', id: 'sales-enablement/sales-strategies-checklist'},
      items: [{type: 'autogenerated', dirName: '07-sales-enablement'}],
    },
    {
      type: 'category',
      label: 'Systems & Automation',
      link: {type: 'doc', id: 'systems-and-automation/systems-and-automation-checklist'},
      items: [{type: 'autogenerated', dirName: '08-systems-and-automation'}],
    },
    {
      type: 'category',
      label: 'Analytics',
      link: {type: 'doc', id: 'analytics/analytics-and-tracking-checklist'},
      items: [{type: 'autogenerated', dirName: '09-analytics'}],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'reference/build-and-qc'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Templates',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'templates'}],
    },
  ],
};

export default sidebars;
